spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_react
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
thymeleaf:
    cache: false
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes:
      - cookie
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
